MPTEditor/Controllers/EditorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MPTEditor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MPTEditor.Controllers
{
    public class EditorController : Controller
    {
        public ApplicationContext db;

        public EditorController(ApplicationContext content)
        {
            this.db = content;
        }
        public async Task<IActionResult> UpdeteTable()
        {
            int ID = Convert.ToInt32(Request.Query["ID"]);
            int value = Convert.ToInt32(Request.Query["Value"]);
            int idRecord = Convert.ToInt32(Request.Query["ID_Record"]);
            if (value == 1) { value = 2; } else { value = 1; };

            var repos = await (from m in db.Attendance
                         select new DobleAttendance
                         {
                             Id_Record = m.Id_Record,
                             Contract_id = m.Contract_id,
                             Month = m.Month,
                             Year = m.Year,
                             dates = new List<int>() {m.one , m.two ,m.three ,m.four ,m.five ,m.six ,m.seven ,m.eight
                                            ,m.nine ,m.ten ,m.eleven ,m.twelve ,m.thirteen ,m.fourteen ,m.fifteen ,m.sixteen
                                            ,m.seventeen ,m.eighteen ,m.nineteen ,m.twenty ,m.twentyOne ,m.twentyTwo ,m.twentyThree
                                            ,m.twentyFour ,m.twentyFive ,m.twentySix ,m.twentySeven ,m.twentyEight ,m.twentyNine ,m.thirty ,m.thirtyOne}
                         }).ToListAsync();
            var whereRepos = repos.Where(p => p.Id_Record == idRecord); 
            Attendance attendance = new Attendance {
                Id_Record = whereRepos.First().Id_Record,
                Contract_id = whereRepos.First().Contract_id,
                Month = whereRepos.First().Month,
                Year = whereRepos.First().Year,
                one= whereRepos.First().dates[0],
                two= whereRepos.First().dates[1],
                three= whereRepos.First().dates[2],
                four= whereRepos.First().dates[3],
                five= whereRepos.First().dates[4],
                six= whereRepos.First().dates[5],
                seven= whereRepos.First().dates[6],
                eight= whereRepos.First().dates[7],
                nine= whereRepos.First().dates[8],
                ten= whereRepos.First().dates[9],
                eleven= whereRepos.First().dates[10],
                twelve= whereRepos.First().dates[11],
                thirteen= whereRepos.First().dates[12],
                fourteen= whereRepos.First().dates[13],
                fifteen= whereRepos.First().dates[14],
                sixteen= whereRepos.First().dates[15],
                seventeen= whereRepos.First().dates[16],
                eighteen= whereRepos.First().dates[17],
                nineteen= whereRepos.First().dates[18],
                twenty= whereRepos.First().dates[19],
                twentyOne= whereRepos.First().dates[20],
                twentyTwo= whereRepos.First().dates[21],
                twentyThree= whereRepos.First().dates[22],
                twentyFour= whereRepos.First().dates[23],
                twentyFive= whereRepos.First().dates[24],
                twentySix= whereRepos.First().dates[25],
                twentySeven= whereRepos.First().dates[26],
                twentyEight = whereRepos.First().dates[27],
                twentyNine= whereRepos.First().dates[28],
                thirty= whereRepos.First().dates[29],
                thirtyOne= whereRepos.First().dates[30]

            };
            switch (ID) {

                case 1:
                    {
                        attendance.one = value;
                    }
                    break;
                case 2:
                    {
                        attendance.two = value;
                    }
                    break;
                case 3:
                    {
                        attendance.three = value;
                    }
                    break;
                case 4:
                    {
                        attendance.four = value;
                    }
                    break;
                case 5:
                    {
                        attendance.five = value;
                    }
                    break;
                case 6:
                    {
                        attendance.six = value;
                    }
                    break;
                case 7:
                    {
                        attendance.seven = value;
                    }
                    break;
                case 8:
                    {
                        attendance.eight = value;
                    }
                    break;
                case 9:
                    {
                        attendance.nine = value;
                    }
                    break;
                case 10:
                    {
                        attendance.ten = value;
                    }
                    break;
                case 11:
                    {
                        attendance.eleven = value;
                    }
                    break;
                case 12:
                    {
                        attendance.twelve = value;
                    }
                    break;
                case 13:
                    {
                        attendance.thirteen = value;
                    }
                    break;
                case 14:
                    {
                        attendance.fourteen = value;
                    }
                    break;
                case 15:
                    {
                        attendance.fifteen = value;
                    }
                    break;
                case 16:
                    {
                        attendance.sixteen = value;
                    }
                    break;
                case 17:
                    {
                        attendance.seventeen = value;
                    }
                    break;
                case 18:
                    {
                        attendance.eighteen = value;
                    }
                    break;
                case 19:
                    {
                        attendance.nineteen = value;
                    }
                    break;
                case 20:
                    {
                        attendance.twenty = value;
                    }
                    break;
                case 21:
                    {
                        attendance.twentyOne = value;
                    }
                    break;
                case 22:
                    {
                        attendance.twentyTwo = value;
                    }
                    break;
                case 23:
                    {
                        attendance.twentyThree = value;
                    }
                    break;
                case 24:
                    {
                        attendance.twentyFour = value;
                    }
                    break;
                case 25:
                    {
                        attendance.twentyFive = value;
                    }
                    break;
                case 26:
                    {
                        attendance.twentySix = value;
                    }
                    break;
                case 27:
                    {
                        attendance.twentySeven = value;
                    }
                    break;
                case 28:
                    {
                        attendance.twentyEight = value;
                    }
                    break;
                case 29:
                    {
                        attendance.twentyNine = value;
                    }
                    break;
                case 30:
                    {
                        attendance.thirty = value;
                    }
                    break;
                case 31:
                    {
                        attendance.thirtyOne = value;
                    }
                    break;
            }

            await db.SaveChangesAsync();

            db.Update(attendance);

            await db.SaveChangesAsync();
            return RedirectToAction(nameof(EditTableAttendance));
        }
        
        public async Task<IActionResult> UpdeteTablePayment()
        {
            int ID = Convert.ToInt32(Request.Query["ID"]);
            int value = Convert.ToInt32(Request.Query["Value"]);
            int idRecord = Convert.ToInt32(Request.Query["ID_Record"]);
            if (value == 1) { value = 2; } else { value = 1; };

            var repos = await (from m in db.Payment_register
                               select new DoblePayment
                               {
                                   Id_Record = m.Id_Record,
                                   Contract_id = m.Contract_id,
                                   Month = m.Month,
                                   Year = m.Year,
                                   dates = new List<int>() {m.one , m.two ,m.three ,m.four ,m.five ,m.six ,m.seven ,m.eight
                                            ,m.nine ,m.ten ,m.eleven ,m.twelve ,m.thirteen ,m.fourteen ,m.fifteen ,m.sixteen
                                            ,m.seventeen ,m.eighteen ,m.nineteen ,m.twenty ,m.twentyOne ,m.twentyTwo ,m.twentyThree
                                            ,m.twentyFour ,m.twentyFive ,m.twentySix ,m.twentySeven ,m.twentyEight ,m.twentyNine ,m.thirty ,m.thirtyOne}
                               }).ToListAsync();

            var whereRepos = repos.Where(p => p.Id_Record == idRecord);

MPTEditor/Views/Editor/AddAttendance.cshtml
@model MPTEditor.Models.Attendance;
@{Layout = "_Layout";}
<div class="container">
    <form class="form-horizontal" asp-antiforgery="true" asp-controller="Editor" asp-action="AddAttendance">
        <span class="heading">Добавление записи</span>
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <input type="number" asp-for="Year" class="form-control" id="inputEmail" placeholder="Год: 2021">
            <span asp-validation-for="Year" />

        </div>
        <div class="form-group">
            <input type="text" asp-for="Month" class="form-control" id="inputFirst" placeholder="Месяц: март">
            <span asp-validation-for="Month" />

        </div>
        <div class="form-group">
            <input type="number" asp-for="Contract_id" class="form-control" id="inputLast" placeholder="1-10000">
            <span asp-validation-for="Contract_id" />

        </div>

        <div class="form-group heading">
            <button type="submit" class="btn btn-default btn-dark ">Добавить</button>
        </div>
    </form>
</div>
  

MPTEditor/Views/Editor/AddListeners.cshtml
@model MPTEditor.Models.Listeners;
@{Layout = "_Layout";}
<div class="container">
    <form class="form-horizontal" asp-antiforgery="true" asp-controller="Editor" asp-action="AddListeners">
        <span class="heading">Добавление слушателя</span>
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <input type="email" asp-for="Email" class="form-control" id="inputEmail" placeholder="E-mail">
            <span asp-validation-for="Email" />

        </div>
        <div class="form-group">
            <input type="text" asp-for="FirstName" class="form-control" id="inputFirst" placeholder="Имя">
            <span asp-validation-for="FirstName" />

        </div>
        <div class="form-group">
            <input type="text" asp-for="LastName" class="form-control" id="inputLast" placeholder="Фамилия">
            <span asp-validation-for="LastName" />

        </div>
        <div class="form-group">
            <input type="text" asp-for="MiddleName" class="form-control" id="inputMiddle" placeholder="Отчество">
            <span asp-validation-for="MiddleName" />

        </div>
        <div class="form-group">
            <input type="number" asp-for="NumberPhone" class="form-control" id="inputNUmber" placeholder="89008007060">
            <span asp-validation-for="NumberPhone" />
        </div>
        <div class="form-group heading">
            <button type="submit" class="btn btn-default btn-dark ">Добавить</button>
        </div>
    </form>

</div>

MPTEditor/Views/Editor/AddPayment.cshtml
@model MPTEditor.Models.PaymentRegister;
@{Layout = "_Layout";}
<div class="container">
    <form class="form-horizontal" asp-antiforgery="true" asp-controller="Editor" asp-action="AddPayment">
        <span class="heading">Добавление записи в реестр</span>
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <input type="number" asp-for="Year" class="form-control" id="inputEmail" placeholder="Год: 2021">
            <span asp-validation-for="Year" />

        </div>
        <div class="form-group">
            <input type="text" asp-for="Month" class="form-control" id="inputFirst" placeholder="Месяц: март">
            <span asp-validation-for="Month" />

        </div>
        <div class="form-group">
            <input type="number" asp-for="Contract_id" class="form-control" id="inputLast" placeholder="1-10000">
            <span asp-validation-for="Contract_id" />

        </div>

        <div class="form-group heading">
            <button type="submit" class="btn btn-default btn-dark ">Добавить</button>
        </div>
    </form>

</div>

MPTEditor/Views/Editor/EditTableAttendance.cshtml
@model IEnumerable<DobleAttendance>
@{
    Layout = "_Layout";
}
<style>
    /* Стили таблицы (IKSWEB) */
    table.iksweb {
        text-decoration: none;
        border-collapse: collapse;
        width: 100%;
        text-align: center;
    }

        table.iksweb th {
            font-weight: normal;
            font-size: 18px;
            color: #ffffff;
            background-color: #343a40;
        }

        table.iksweb td {
            font-size: 17px;
            color: #969696;
        }

        table.iksweb td, table.iksweb th {
            white-space: pre-wrap;
            padding: 10px 5px;
            line-height: 17px;
            vertical-align: middle;
            border: 1px solid #354251;
        }

        table.iksweb tr:hover {
            background-color: #343a40
        }

            table.iksweb tr:hover td {
                color: #ffffff;
                cursor: pointer;
            }

    .mobile-table {
        width: 100%;
        max-width: 100%;
        overflow-x: auto;
    }
</style>
<div style="background-color:white">

    <div class="mobile-table">
        @if (Model == null)
        {
            <a>Коллекция пуста!</a>
        }
        else
        {

            <table class="iksweb">
                <thead>
                    <tr>

                        <th>Статус</th>
                        <th>ФИО</th>
                        <th>Код договора</th>
                        <th>Месяц</th>
                        <th>Год</th>
                        @for (int i = 1; i <= 31; i++)
                        {
                            <th>@i</th>

                        }
                    </tr>
                </thead>
                <tbody>
                    @{ foreach (var Record in Model)
                        {
                            <tr>
                                <td><a class="btn btn-danger" href="~/Editor/DeleteAttendance?ID=@Record.Id_Record">Удалить</a></td>
                                <td>@Record.FIO</td>
                                <td>@Record.Code_contract</td>
                                <td>@Record.Month</td>
                                <td>@Record.Year</td>

                                @for (int date = 1; date < 32; date++)
                                {
                                    if (Record.dates[date - 1] == 1)
                                    {
                                        <td><a class="btn btn-danger" href="~/Editor/UpdeteTable?ID=@date&Value=1&ID_Record=@Record.Id_Record">-</a></td>
                                    }
                                    else if (Record.dates[date - 1] == 2)
                                    {
                                        <td><a class="btn btn-primary" href="~/Editor/UpdeteTable?ID=@date&Value=2&ID_Record=@Record.Id_Record">+</a></td>
                                    }
                                    else
                                    {
                                        <td><a class="btn btn-light" href="~/Editor/UpdeteTable?ID=@date&Value=1&ID_Record=@Record.Id_Record"> </a></td>
                                    }
                                }
                            </tr>
                        }
                    }
                </tbody>
            </table>
        }
    </div>
    <a class="btn btn-primary" href="~/Editor/AddAttendance">Добавить запись</a>

</div>

MPTEditor/Views/Editor/EditTablePayment.cshtml
@model IEnumerable<DoblePayment>
@{
    Layout = "_Layout";
}
<style>
    /* Стили таблицы (IKSWEB) */
    table.iksweb {
        text-decoration: none;
        border-collapse: collapse;
        width: 100%;
        text-align: center;
    }

        table.iksweb th {
            font-weight: normal;
            font-size: 18px;
            color: #ffffff;
            background-color: #343a40;
        }

        table.iksweb td {
            font-size: 17px;
            color: #969696;
        }

        table.iksweb td, table.iksweb th {
            white-space: pre-wrap;
            padding: 10px 5px;
            line-height: 17px;
            vertical-align: middle;
            border: 1px solid #354251;
        }

        table.iksweb tr:hover {
            background-color: #343a40
        }

            table.iksweb tr:hover td {
                color: #ffffff;
                cursor: pointer;
            }

    .mobile-table {
        width: 100%;
        max-width: 100%;
        overflow-x: auto;
    }
</style>
<div style="background-color:white">

    <div class="mobile-table">
        @if (Model == null)
        {
            <a>Коллекция пуста!</a>
        }
        else
        {

            <table class="iksweb">
                <thead>
                    <tr>
                        <th>Статус</th>
                        <th>ФИО</th>
                        <th>Код договора</th>
                        <th>Месяц</th>
                        <th>Год</th>
                        @for (int i = 1; i <= 31; i++)
                        {
                            <th>@i</th>

                        }
                    </tr>
                </thead>
                <tbody>
                    @{ foreach (var Record in Model)
                        {
                        <tr>
                            <td><a class="btn btn-danger" href="~/Editor/DeletePayment?ID=@Record.Id_Record">Удалить</a></td>
                            <td>@Record.FIO</td>
                            <td>@Record.Code_contract</td>
                            <td>@Record.Month</td>
                            <td>@Record.Year</td>

                            @for (int date = 1; date < 32; date++)
                            {
                                if (Record.dates[date-1] == 1)
                                {<td><a class="btn btn-danger" href="~/Editor/UpdeteTablePayment?ID=@date&Value=1&ID_Record=@Record.Id_Record"> </a></td>}
                                else if (Record.dates[date-1] == 2)
                                {<td><a class="btn btn-primary" href="~/Editor/UpdeteTablePayment?ID=@date&Value=2&ID_Record=@Record.Id_Record">Оплачен</a></td> }
                                else
                                {<td><a class="btn btn-danger" href="~/Editor/UpdeteTablePayment?ID=@date&Value=1&ID_Record=@Record.Id_Record"> </a></td>}
                            }
                        </tr>
                            }
                        }
                </tbody>
            </table>
        }

    </div>
    <a class="btn btn-primary" href="~/Editor/AddPayment">Добавить запись в Реестр оплаты</a>
</div>

MPTEditor/Views/Editor/ListListeners.cshtml
@model IEnumerable<Listeners>
@{
    Layout = "_Layout";
}
<style>
    /* Стили таблицы (IKSWEB) */
    table.iksweb {
        text-decoration: none;
        border-collapse: collapse;
        width: 100%;
        text-align: center;
    }

        table.iksweb th {
            font-weight: normal;
            font-size: 18px;
            color: #ffffff;
            background-color: #343a40;
        }

        table.iksweb td {
            font-size: 17px;
            color: #969696;
        }

        table.iksweb td, table.iksweb th {
            white-space: pre-wrap;
            padding: 10px 5px;
            line-height: 17px;
            vertical-align: middle;
            border: 1px solid #354251;
        }

        table.iksweb tr:hover {
            background-color: #343a40
        }

            table.iksweb tr:hover td {
                color: #ffffff;
                cursor: pointer;
            }

    .mobile-table {
        width: 100%;
        max-width: 100%;
        overflow-x: auto;
    }
</style>
<div class="container" style="background-color:white">

    <div class="mobile-table">
        @if (Model == null)
        {
            <a>Коллекция пуста!</a>
        }
        else
        {

            <table class="iksweb">
                <thead>
                    <tr>
                        <th>ФИО</th>
                        <th>Номер телефона</th>
                        <th>Почта</th>

                    </tr>
                </thead>
                <tbody>
                    @{ foreach (var Record in Model)
                        {
                            <tr>
                                <td>@Record.FirstName @Record.LastName @if (Record.MiddleName != null)@Record.MiddleName  </td>
                                <td>@Record.NumberPhone</td>
                                <td>@Record.Email</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        }
    </div>
</div>